import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Graph from '../components/graph'
import styles from '../styles/Home.module.css'
import { GraphData } from '../type'
import { getData } from '../utils/handleData'

const Home: NextPage = () => {

  const [graphData, setGraphData] = useState<GraphData>(null!)

  useEffect(() => {
    getData(0).then(val => setGraphData({
      edges: val.edges,
      nodes: {
        ...val
      }
    }))
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ width: '100%', height: '100vh' }}>
          <Graph {...graphData} />
        </div>
      </main>
    </div>
  )
}

export default Home
